### ISSUE TITLE
save_dir has no effect

### ISSUE THREAD

**Issue by huyaoyu** [castacks/tartancalib#9]
The `--save_dir` argument seems to behave in the wrong way. For example, I specified

```bash
--save_dir /data/5ms_01/result
```

But the results are actually saved to `/data/5ms_01`. 

The issue is that I don't have a slash symbol ("/") at the end of `result`. And the result files will all have a `result` prefix.

But when I add the slash, the program will complain about that the target file location does not exist if I did not create the target directory before running the program. I think it might be more appropriate to create the target folder automatically for the user. The users will be really disappointed when they found that the program fails after a long wait only because they have forgotten to create the target folder beforehand.

**Comment by huyaoyu** [comment]
More context for debugging.

Here is the error message with a non-exist file location.

```
Traceback (most recent call last):
  File "/catkin_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/ConfigReader.py", line 222, in writeYaml                                                                                      
    with open(filename, 'w') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: '/ocean/projects/cis220039p/yaoyuh/WD/dsta/calib_202301/5ms_02/scripts/../result/log0-camchain.yaml' 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/catkin_ws/devel/lib/kalibr/tartan_calibrate", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/catkin_ws/src/kalibr/aslam_offline_calibration/kalibr/python/tartan_calibrate", line 656, in <module>                                                                                                    
    main()
  File "/catkin_ws/src/kalibr/aslam_offline_calibration/kalibr/python/tartan_calibrate", line 613, in main                                                                                                        
    kcc.saveChainParametersYaml(calibrator, resultFile, graph)
  File "/catkin_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/CameraCalibrator.py", line 789, in saveChainParametersYaml                                                        
    chain.writeYaml()
  File "/catkin_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/ConfigReader.py", line 225, in writeYaml                                                                                      
    self.raiseError( "Could not write configuration to {0}".format(self.yamlFile) )
  File "/catkin_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/ConfigReader.py", line 235, in raiseError                                                                                     
    raise RuntimeError( "{0}{1}".format(header, message) )
RuntimeError: [CameraChainParameters Reader]: Could not write configuration to /ocean/projects/cis220039p/yaoyuh/WD/dsta/calib_202301/5ms_02/scripts/../result/log0-camchain.yaml
```

**Comment by Duisterhof** [comment]
This sounds like a good feature, I can have a look at it later this week or if you already have something working locally you can make a pull request.
